//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECU_Text.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECU_Text.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN SOURCE application.
        /// </summary>
        public static string AboutLiteral1 {
            get {
                return ResourceManager.GetString("AboutLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available on:.
        /// </summary>
        public static string AboutLiteral2 {
            get {
                return ResourceManager.GetString("AboutLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to most recent..
        /// </summary>
        public static string AboutLiteral3 {
            get {
                return ResourceManager.GetString("AboutLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application developed by:.
        /// </summary>
        public static string AboutLiteral4 {
            get {
                return ResourceManager.GetString("AboutLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated to my daughter Valentina, I love you daughter!!!.
        /// </summary>
        public static string AboutLiteral5 {
            get {
                return ResourceManager.GetString("AboutLiteral5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item type..
        /// </summary>
        public static string AddItemLiteral1 {
            get {
                return ResourceManager.GetString("AddItemLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a title name for item..
        /// </summary>
        public static string AddItemLiteral2 {
            get {
                return ResourceManager.GetString("AddItemLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the content for item..
        /// </summary>
        public static string AddItemLiteral3 {
            get {
                return ResourceManager.GetString("AddItemLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the new item?.
        /// </summary>
        public static string AddItemLiteral4 {
            get {
                return ResourceManager.GetString("AddItemLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the item..
        /// </summary>
        public static string AddItemLiteral5 {
            get {
                return ResourceManager.GetString("AddItemLiteral5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the changes?.
        /// </summary>
        public static string AddItemLiteral6 {
            get {
                return ResourceManager.GetString("AddItemLiteral6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECURE-Text.
        /// </summary>
        public static string AppLiteral1 {
            get {
                return ResourceManager.GetString("AppLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string AppLiteral2 {
            get {
                return ResourceManager.GetString("AppLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your text here....
        /// </summary>
        public static string AppLiteral3 {
            get {
                return ResourceManager.GetString("AppLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press back button.
        /// </summary>
        public static string AppLiteral4 {
            get {
                return ResourceManager.GetString("AppLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times more to exit the app..
        /// </summary>
        public static string AppLiteral5 {
            get {
                return ResourceManager.GetString("AppLiteral5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added....
        /// </summary>
        public static string AppLiteral6 {
            get {
                return ResourceManager.GetString("AppLiteral6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item updated....
        /// </summary>
        public static string AppLiteral7 {
            get {
                return ResourceManager.GetString("AppLiteral7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item deleted....
        /// </summary>
        public static string AppLiteral8 {
            get {
                return ResourceManager.GetString("AppLiteral8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the item?.
        /// </summary>
        public static string EditItemLiteral1 {
            get {
                return ResourceManager.GetString("EditItemLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item could not be updated..
        /// </summary>
        public static string EditItemLiteral2 {
            get {
                return ResourceManager.GetString("EditItemLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ExceptionLiteral1 {
            get {
                return ResourceManager.GetString("ExceptionLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        public static string ExceptionLiteral2 {
            get {
                return ResourceManager.GetString("ExceptionLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ExceptionLiteral3 {
            get {
                return ResourceManager.GetString("ExceptionLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string HomePageDetailLiteral1 {
            get {
                return ResourceManager.GetString("HomePageDetailLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageMasterLiteral1 {
            get {
                return ResourceManager.GetString("HomePageMasterLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string HomePageMasterLiteral2 {
            get {
                return ResourceManager.GetString("HomePageMasterLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string HomePageMasterLiteral3 {
            get {
                return ResourceManager.GetString("HomePageMasterLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HomePageMasterLiteral4 {
            get {
                return ResourceManager.GetString("HomePageMasterLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Codes.
        /// </summary>
        public static string ItemTypeLiteral1 {
            get {
                return ResourceManager.GetString("ItemTypeLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Information.
        /// </summary>
        public static string ItemTypeLiteral2 {
            get {
                return ResourceManager.GetString("ItemTypeLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string ItemTypeLiteral3 {
            get {
                return ResourceManager.GetString("ItemTypeLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Cards.
        /// </summary>
        public static string ItemTypeLiteral4 {
            get {
                return ResourceManager.GetString("ItemTypeLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Notes.
        /// </summary>
        public static string ItemTypeLiteral5 {
            get {
                return ResourceManager.GetString("ItemTypeLiteral5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch the fingerprint sensor....
        /// </summary>
        public static string LoginLiteral1 {
            get {
                return ResourceManager.GetString("LoginLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password..
        /// </summary>
        public static string LoginLiteral2 {
            get {
                return ResourceManager.GetString("LoginLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password..
        /// </summary>
        public static string LoginLiteral3 {
            get {
                return ResourceManager.GetString("LoginLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App blocked.
        /// </summary>
        public static string LoginLiteral4 {
            get {
                return ResourceManager.GetString("LoginLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password....
        /// </summary>
        public static string LoginLiteral5 {
            get {
                return ResourceManager.GetString("LoginLiteral5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string LoginLiteral6 {
            get {
                return ResourceManager.GetString("LoginLiteral6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch the fingerprint image.
        /// </summary>
        public static string LoginLiteral7 {
            get {
                return ResourceManager.GetString("LoginLiteral7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and restore.
        /// </summary>
        public static string OptionsLiteral1 {
            get {
                return ResourceManager.GetString("OptionsLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restored successfully..
        /// </summary>
        public static string OptionsLiteral10 {
            get {
                return ResourceManager.GetString("OptionsLiteral10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to restore a backup..
        /// </summary>
        public static string OptionsLiteral11 {
            get {
                return ResourceManager.GetString("OptionsLiteral11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want make a backup, this option will overwrite an older backup?.
        /// </summary>
        public static string OptionsLiteral12 {
            get {
                return ResourceManager.GetString("OptionsLiteral12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want restore a backup, this option will overwrite the current data?.
        /// </summary>
        public static string OptionsLiteral13 {
            get {
                return ResourceManager.GetString("OptionsLiteral13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation make and restore a backup on external storage, download folder..
        /// </summary>
        public static string OptionsLiteral14 {
            get {
                return ResourceManager.GetString("OptionsLiteral14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a backup:.
        /// </summary>
        public static string OptionsLiteral2 {
            get {
                return ResourceManager.GetString("OptionsLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKUP.
        /// </summary>
        public static string OptionsLiteral3 {
            get {
                return ResourceManager.GetString("OptionsLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore a backup:.
        /// </summary>
        public static string OptionsLiteral4 {
            get {
                return ResourceManager.GetString("OptionsLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESTORE.
        /// </summary>
        public static string OptionsLiteral5 {
            get {
                return ResourceManager.GetString("OptionsLiteral5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external storage can not be read or write, give access on application configurations in OS options..
        /// </summary>
        public static string OptionsLiteral6 {
            get {
                return ResourceManager.GetString("OptionsLiteral6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created successfully..
        /// </summary>
        public static string OptionsLiteral7 {
            get {
                return ResourceManager.GetString("OptionsLiteral7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to create backup..
        /// </summary>
        public static string OptionsLiteral8 {
            get {
                return ResourceManager.GetString("OptionsLiteral8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file does not exist, nothing to restore..
        /// </summary>
        public static string OptionsLiteral9 {
            get {
                return ResourceManager.GetString("OptionsLiteral9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password..
        /// </summary>
        public static string RegisterLiteral1 {
            get {
                return ResourceManager.GetString("RegisterLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create password..
        /// </summary>
        public static string RegisterLiteral2 {
            get {
                return ResourceManager.GetString("RegisterLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create password.
        /// </summary>
        public static string RegisterLiteral3 {
            get {
                return ResourceManager.GetString("RegisterLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string RegisterLiteral4 {
            get {
                return ResourceManager.GetString("RegisterLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password..
        /// </summary>
        public static string SecurityLiteral1 {
            get {
                return ResourceManager.GetString("SecurityLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated..
        /// </summary>
        public static string SecurityLiteral2 {
            get {
                return ResourceManager.GetString("SecurityLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update password..
        /// </summary>
        public static string SecurityLiteral3 {
            get {
                return ResourceManager.GetString("SecurityLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication by fingerprint enabled..
        /// </summary>
        public static string SecurityLiteral4 {
            get {
                return ResourceManager.GetString("SecurityLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication by fingerprint disabled..
        /// </summary>
        public static string SecurityLiteral5 {
            get {
                return ResourceManager.GetString("SecurityLiteral5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable FingerPrint..
        /// </summary>
        public static string SecurityLiteral6 {
            get {
                return ResourceManager.GetString("SecurityLiteral6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change.
        /// </summary>
        public static string SecurityLiteral7 {
            get {
                return ResourceManager.GetString("SecurityLiteral7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable FingerPrint:.
        /// </summary>
        public static string SecurityLiteral8 {
            get {
                return ResourceManager.GetString("SecurityLiteral8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item data copied to clipboard..
        /// </summary>
        public static string ViewItemLiteral1 {
            get {
                return ResourceManager.GetString("ViewItemLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item title:.
        /// </summary>
        public static string ViewItemLiteral10 {
            get {
                return ResourceManager.GetString("ViewItemLiteral10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item data:.
        /// </summary>
        public static string ViewItemLiteral11 {
            get {
                return ResourceManager.GetString("ViewItemLiteral11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the current item?.
        /// </summary>
        public static string ViewItemLiteral2 {
            get {
                return ResourceManager.GetString("ViewItemLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string ViewItemLiteral3 {
            get {
                return ResourceManager.GetString("ViewItemLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string ViewItemLiteral4 {
            get {
                return ResourceManager.GetString("ViewItemLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current item could not be deleted..
        /// </summary>
        public static string ViewItemLiteral5 {
            get {
                return ResourceManager.GetString("ViewItemLiteral5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy item data.
        /// </summary>
        public static string ViewItemLiteral6 {
            get {
                return ResourceManager.GetString("ViewItemLiteral6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        public static string ViewItemLiteral7 {
            get {
                return ResourceManager.GetString("ViewItemLiteral7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        public static string ViewItemLiteral8 {
            get {
                return ResourceManager.GetString("ViewItemLiteral8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item type:.
        /// </summary>
        public static string ViewItemLiteral9 {
            get {
                return ResourceManager.GetString("ViewItemLiteral9", resourceCulture);
            }
        }
    }
}
